### ISSUE TITLE
Adding comment to order fails

### ISSUE THREAD

**Issue by clicktrend** [mirasvit/module-profiler#12]
Facing that error when adding comment to order

```
2017/06/19 09:59:11 [error] 32488#32488: *93318 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Zend_Controller_Plugin_Abstract::setResponse() must be an instance of Zend_Controller_Response_Abstract, instance of Magento\Framework\HTTP\PhpEnvironment\Response given, called in /var/www/example/www/production/releases/20170602144729/vendor/magento/framework/Profiler/Driver/Standard/Output/Firebug.php on line 61 and defined in /var/www/example/www/production/releases/20170602144729/vendor/magento/zendframework1/library/Zend/Controller/Plugin/Abstract.php:70
Stack trace:
#0 /var/www/example/www/production/releases/20170602144729/vendor/magento/framework/Profiler/Driver/Standard/Output/Firebug.php(61): Zend_Controller_Plugin_Abstract->setResponse(Object(Magento\Framework\HTTP\PhpEnvironment\Response))
#1 /var/www/example/www/production/releases/20170602144729/vendor/magento/framework/Profiler/Driver/Standard.php(195): Magento\Framework\Profiler\Driver\Standard\Output\Firebug->display(Object(Magento\Framework\P" while reading response header from upstream, client: 10.99.0.19, server: www.example.de, request: "POST /adm_n/sales/order/addComment/order_id/17466/key/8af67ddd1762355fdc42ae9f292211daa5a23da0b2dd1519aef2d567d00f2566/?isAjax=true HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "www.example.de", referrer: "https://www.example.de/adm_n/sales/order/view/order_id/17466/key/37f07c7afffa913886c27d4db73964b59b266cecab2b464af9a2fa77f6fffe48/"

```

Magento: 2.1.7 + PHP7

**Comment by clicktrend** [comment]
Sorry wrong project
