### ISSUE TITLE
Unable to write using YAML Dumper.

### ISSUE THREAD

**Issue by nitin700** [mirasvit/module-profiler#25]
Hi,

I am facing this issue while enabling this profiler module.
please help to get this issue resolve.

```
C:\wamp64\www\MyProjects\Magento22Comp>php -f bin/magento mirasvit:profiler:enable
Status: Enabled

Fatal error: Uncaught Exception: Warning: file_put_contents(C:/wamp64/www/MyProjects/Magento22Comp/var/profiler/2017-11-19 09:29:24.274500.meta): fail
\wamp64\www\MyProjects\Magento22Comp\vendor\mirasvit\module-profiler\src\Profiler\Model\Storage.php on line 48 in C:\wamp64\www\MyProjects\Magento22Co
1
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'file_put_conten...', 'C:\\wamp64\\www\\M...', 48, Array)
#1 C:\wamp64\www\MyProjects\Magento22Comp\vendor\mirasvit\module-profiler\src\Profiler\Model\Storage.php(48): file_put_contents('C:/wamp64/www/M...',
#2 C:\wamp64\www\MyProjects\Magento22Comp\vendor\mirasvit\module-profiler\src\Profiler\Model\Driver\Output\Html.php(39): Mirasvit\Profiler\Model\Stora
#3 C:\wamp64\www\MyProjects\Magento22Comp\vendor\magento\framework\Profiler\Driver\Standard.php(195): Mirasvit\Profiler\Model\Driver\Output\Html->disp
mp\vendor\magento\framework\App\ErrorHandler.php on line 61
```
for more clarification, i already executed below command and package is available. But still getting above error.
`composer require symphony/yaml`
Magenot Version 2.2.0

Regards,
Nitin

**Comment by welkinstest** [comment]
Hi,

I am also facing same error...Any one have solution?. Please share it here.
