### ISSUE TITLE
Issue when enabled profiler

### ISSUE THREAD

**Issue by devamitbera** [mirasvit/module-profiler#36]
Use this command 

>  php -d memory_limit=10G  bin/magento  mirasvit:profiler:enable

to enable the profiler and getting the this issue:

```
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Yaml\Dumper' not found in /var/www/html/vendor/mirasvit/module-profiler/src/Profiler/Model/Storage.php:48
Stack trace:
#0 /var/www/html/vendor/mirasvit/module-profiler/src/Profiler/Model/Driver/Output/Html.php(39): Mirasvit\Profiler\Model\Storage->dump()
#1 /var/www/html/vendor/magento/framework/Profiler/Driver/Standard.php(195): Mirasvit\Profiler\Model\Driver\Output\Html->display(Object(Magento\Framework\Profiler\Driver\Standard\Stat))
#2 [internal function]: Magento\Framework\Profiler\Driver\Standard->display()
#3 {main}
  thrown in /var/www/html/vendor/mirasvit/module-profiler/src/Profiler/Model/Storage.php on line 48



```
Why issue are coming ?

**Comment by paales** [comment]
Having the same issue

**Comment by adrok** [comment]
Run command composer require symfony/yaml for install yaml dumper.

**Comment by paales** [comment]
Oh, it seems to be fixed in the latest branch, but isn't released yet.

Run `composer require mirasvit/module-profiler dev-master`

**Comment by paales** [comment]
>  Run command composer require symfony/yaml for install yaml dumper.

That doesn't work, you will get version conflicts.

**Comment by fauzie** [comment]
##### Magento 2.2.0 EE B2B Version

Default install & run upgrade, compile, etc.

```
Fatal error: Uncaught Error: Class 'Symfony\Component\Yaml\Dumper' not found in /magento/vendor/mirasvit/module-profiler/src/Profiler/Model/Storage.php:48
```
```$ composer require symfony/yaml```
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install symfony/yaml v4.1.4
    - Conclusion: don't install symfony/yaml v4.1.3
    - Conclusion: don't install symfony/yaml v4.1.2
    - Conclusion: don't install symfony/yaml v4.1.1
    - symfony/yaml v4.1.0 conflicts with symfony/console[v2.8.38].
    - symfony/yaml v4.1.0 conflicts with symfony/console[v2.8.38].
    - symfony/yaml v4.1.0 conflicts with symfony/console[v2.8.38].
    - Installation request for symfony/yaml ^4.1 -> satisfiable by symfony/yaml[v4.1.0, v4.1.1, v4.1.2, v4.1.3, v4.1.4].
    - Installation request for symfony/console (locked at v2.8.38) -> satisfiable by symfony/console[v2.8.38].
```
```$ composer require mirasvit/module-profiler dev-master```
```
Problem 1
    - Conclusion: remove symfony/console v2.8.38
    - Conclusion: don't install symfony/console v2.8.38
    - etc.......
```

Please help!

**Comment by ansyori** [comment]
composer require symfony/yaml:dev-issue-8145
